ManageXR/mxr-unity-sdk

- Assets/MXR.SDK/Plugins/Android/NativeUtils.java
- Assets/MXR.SDK/Runtime/Android/Utils/MXRAndroidUtils.Apps.cs
- Assets/MXR.SDK/Runtime/Types/RuntimeTypes.cs
Add SendBroadcastAction function. Set HOME_SCREEN as default deviceExperienceMode for legacy reasons.
> Updates for Advanced Shortcut Menu release

- Assets/MXR.SDK/package.json
Release with HomeScreenState, Command, Command Simulater
> Bump version to 0.0.9

- Assets/MXR.SDK/Runtime/Android/Utils/MXRAndroidUtils.Device.cs
This is needed for Pico 4 support in the home screen
> Add helper function to determine if a device is a Pico 4

- .github/workflows/ci.yml
Angular commit analyzer used. Refer to committing guidelines here: https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines
> Enable semantic release action and auto github tag creation [skip ci]

- Assets/MXR.SDK/Editor/MXRCommandSimulator.cs
- Assets/MXR.SDK/Runtime/Android/MXRAndroidSystem.cs
- Assets/MXR.SDK/Runtime/Android/Utils/MXRAndroidUtils.cs
- Assets/MXR.SDK/Runtime/Editor/MXREditorSystem.cs
- Assets/MXR.SDK/Runtime/IMXRSystem.cs
- Assets/MXR.SDK/Runtime/MXRManager.cs
- Assets/MXR.SDK/Runtime/Types/CommandTypes.cs
- Assets/MXR.SDK/Runtime/Utils/Dispatcher.cs
- Assets/MXR.SDK/package.json
- MXRAndroidSystem handles the flattened command related fields. Currently only handles PLAY_VIDEO action.
- Added some required intent related utility methods to MXRAndroidUtils
- Improved logging throughout the SDK
> Handling of intent commands

- Assets/MXR.SDK/Plugins/Android/AdminAppMessageTypes.java
- Assets/MXR.SDK/Plugins/Android/AdminAppMessengerManager.java
- Assets/MXR.SDK/Runtime/Android/MXRAndroidSystem.cs
- Assets/MXR.SDK/Runtime/MXRManager.cs
- Assets/MXR.SDK/Runtime/Types/HomeScreenTypes.cs
- Added sendHomeScreenState method in AdminAppMessengerManager.java for sending state to admin app
- Implemented SendHomeScreenState method in MXRAndroidSystem
- Updates to HomeScreen state types for json serialization purposes
> Added Home Screen state reporting

- Assets/MXR.SDK/Plugins/Android/AdminAppMessageTypes.java
- Assets/MXR.SDK/Plugins/Android/AdminAppMessengerManager.java
- Assets/MXR.SDK/Plugins/Android/NativeUtils.java
- Assets/MXR.SDK/Runtime/Android/MXRAndroidSystem.cs
- Assets/MXR.SDK/Runtime/Android/Utils/MXRAndroidUtils.Apps.cs
- Assets/MXR.SDK/Runtime/Editor/MXREditorSystem.cs
- Assets/MXR.SDK/Runtime/IMXRSystem.cs
https://app.clickup.com/t/8669kqjwq
> #8669kqjwq - Add kill and restart app messages so we can rely on the admin app to handle these functions

- Assets/MXR.SDK/README.md
- Assets/MXR.SDK/Runtime/Android/Utils/MXRAndroidUtils.Apps.cs
- Assets/MXR.SDK/Runtime/Android/Utils/MXRAndroidUtils.Device.cs
- README.md
Updated README for permission granting.
> Added utilities for Android12 storage access

- Assets/MXR.SDK/Runtime/Android/Utils/MXRAndroidUtils.Device.cs
https://app.clickup.com/t/8684uh0m5
> Indicate Pico 4 devices as 6DOF and update some model numbers

- Assets/MXR.SDK/Plugins/Android/NativeUtils.java
- Assets/MXR.SDK/Runtime/Android/Utils/MXRAndroidUtils.Apps.cs
To be used for compatibility checks
> Add a Util to get the installed admin app version code

- Assets/MXR.SDK/Runtime/Types/WifiTypes.cs
- Added new field `hidden `and SDK Enum `NetworkType `to EnterpriseWifiConnectionRequest
> Hidden Wifi Network

- Assets/MXR.SDK/Runtime/Android/Utils/MXRAndroidUtils.Device.cs
Do the same for other models and manufacturers for future proofing
> Ignore case when checking manufacturer for Pico vs PICO. 

- Assets/MXR.SDK/Runtime/Android/Utils/MXRAndroidUtils.Device.cs
- Also added triple slash doc comments
- Also updated the degrees of freedom helpers with new utilities
> Added Pico G3, Focus Plus and XR Series/XR Elite detection code

- Assets/MXR.SDK/Plugins/Android/NativeUtils.java
- Assets/MXR.SDK/package.json
- Updated the Intents with `Intent.FLAG_ACTIVITY_NEW_TASK` flag. A relevant link: https://stackoverflow.com/a/50833599.
- Catch and print exceptions when they happen
> v1.0.10 Use activity new task flag in intents

- Assets/MXR.SDK/Runtime/Types/RuntimeTypes.cs
- Packages/manifest.json
- Packages/packages-lock.json
- Also added the packages for Visual Studio, VS Code and JetBrains Rider, without which opening scripts from Unity can cause problems
> Added passthrough field in HiddenSettings

- Assets/MXR.SDK/README.md
- README.md
- Removed OpenUPM registry as it required more steps. Git URL based installation is quicker, clearer and does the same things.
- Added links and notes about release versions
> Recommend git URL installation

- Assets/MXR.SDK/Runtime/Types/StatusTypes.cs
Ensures that it isn't null by default.
Also updated some codedoc comments.
> DeviceStatus.controllerData is declared with 'new'

- Assets/MXR.SDK/Editor/README.md
- Assets/MXR.SDK/Runtime/Android/MXRAndroidSystem.cs
- Assets/MXR.SDK/Runtime/Editor/MXREditorSystem.cs
- Assets/MXR.SDK/Runtime/IMXRSystem.cs
- Assets/MXR.SDK/Runtime/Types/CommandTypes.cs
- Assets/MXR.SDK/Samples/Scripts/CommandSubscriberExample.cs
See internal PR https://github.com/ManageXR/custom-launcher/pull/546
> CU-868b16mc2 Resume video support SDK changes

- Assets/MXR.SDK/Runtime/Types/RuntimeTypes.cs
Dutch
Norwegian
Japanese
Korean
> CU-868b9y2cd : More translations 

- Assets/MXR.SDK/Plugins/Android/AdminAppMessengerManager.java
Invokes sendMessage with GET_DEVICE_DATA message code
> CU-868brkjk3: Added getDeviceDataAsync method to AdminAppMessengerManager.java

- Assets/MXR.SDK/Runtime/Types/DeviceTypes.cs
- Assets/MXR.SDK/Runtime/Types/DeviceTypes.cs.meta
> CU-868brkjk3: Added DeviceData class

- Assets/MXR.SDK/Runtime/Android/MXRAndroidSystem.cs
- Assets/MXR.SDK/Runtime/Editor/MXREditorSystem.cs
- Assets/MXR.SDK/Runtime/IMXRSystem.cs
MXRAndroidSystem and MXREditorSystem classes have empty implementations right now.
> CU-868brkjk3: DeviceData additions to IMXRSystem

- Assets/MXR.SDK/Runtime/Android/MXRAndroidSystem.cs
The code is similar to DeviceStatus
> CU-868brkjk3: Implemented DeviceData additions in MXRAndroidSystem

- Assets/MXR.SDK/Runtime/Editor/MXREditorSystem.cs
RefreshDeviceData(), similar to RefreshDeviceStatus()
> CU-868brkjk3: Implemented DeviceData additions in MXREditorSystem

- Assets/MXR.SDK/Runtime/Types/RuntimeTypes.cs
See https://github.com/ManageXR/custom-launcher/pull/589
> CU-868btd61m Helper for toggling admin settings

- Assets/MXR.SDK/Runtime/Android/MXRAndroidSystem.cs
The DeviceStatus path was incorrectly used.
> Use correct cached DeviceData path for file initialization

- Assets/MXR.SDK/Runtime/Types/RuntimeTypes.cs
See [the task](https://app.clickup.com/t/868dycu2u) for why and more details.
> CU-868dycu2u: Move environmentFile to backgroundSettings

- Assets/MXR.SDK/Runtime/Types/StatusTypes.cs
Required for serialization of DeviceStatus.fileStatuses dictionary
> Add ManagedFileType.ENVIRONMENT

- README.md
> Add OpenUPM badges to README.md

- Assets/MXR.SDK/Plugins/Android/AdminAppMessageTypes.java
- Assets/MXR.SDK/Plugins/Android/AdminAppMessengerManager.java
- Assets/MXR.SDK/Runtime/Android/MXRAndroidSystem.cs
- Assets/MXR.SDK/Runtime/Editor/MXREditorSystem.cs
- Assets/MXR.SDK/Runtime/IMXRSystem.cs
Added device power management capabilities to the MXR SDK.
- Added new message types `POWER_OFF` and `REBOOT` in `AdminAppMessageTypes.java`
- Implemented `shutdown()` and `reboot()` methods in `AdminAppMessengerManager.java`
- Added corresponding `Shutdown()` and `Reboot()` methods to `MXRAndroidSystem.cs`
- Added implementations for these methods in `MXREditorSystem.cs` for testing in the Unity editor
- Updated the `IMXRSystem.cs` interface with the new method declarations and documentation
> CU-868ecyyq9: Shutdown Reboot from SDK

- Assets/MXR.SDK/Plugins/Android/AdminAppMessageTypes.java
- Assets/MXR.SDK/Plugins/Android/AdminAppMessengerManager.java
- Assets/MXR.SDK/Runtime/Android/MXRAndroidSystem.cs
- Assets/MXR.SDK/Runtime/Editor/MXREditorSystem.cs
- Assets/MXR.SDK/Runtime/IMXRSystem.cs
- Assets/MXR.SDK/Runtime/Types/StatusTypes.cs
- Assets/MXR.SDK/Runtime/Utils/UnixTimeUtils.cs
- Assets/MXR.SDK/Runtime/Utils/UnixTimeUtils.cs.meta
Added streaming code functionality to the MXR SDK for Android.
- Added new message types `GET_STREAMING_CODE` and `STREAMING_CODE` in `AdminAppMessageTypes.java`
- Added `requestStreamingCodeAsync()` method in `AdminAppMessengerManager.java`
- Added streaming code support in `MXRAndroidSystem.cs`:
- Added `StreamingCodeStatus` property and event
- Added handler for streaming code messages
- Added `RequestStreamingCode()` method
- Created new `StreamingCodeStatus` class in `StatusTypes.cs` with `code` and `errorMessage` fields
> CU-868evjqkw: Add Streaming Code Support

- Assets/MXR.SDK/Runtime/Android/MXRAndroidSystem.cs
Refactored the MXRAndroidSystem class to improve code organization, readability, and maintainability.
- Added a private `AdminAppMessageTypes` class to centralize message type constants
- Added XML documentation for the AdminAppMessageTypes class
- Improved method organization with private helper methods for handling different message types
- Enhanced error handling with dedicated logging methods
- Standardized code style with consistent access modifiers and braces
- Extracted message handling logic from the constructor into separate methods
- Improved null checking and conditional logic throughout the class
- Simplified code paths with early returns and better control flow
> CU-868ex4jw0: General MXRAndroidSystem Cleanup

- Assets/MXR.SDK/Runtime/Android/MXRAndroidSystem.Commands.cs
- Assets/MXR.SDK/Runtime/Android/MXRAndroidSystem.Commands.cs.meta
- Assets/MXR.SDK/Runtime/Android/MXRAndroidSystem.Initialization.cs
- Assets/MXR.SDK/Runtime/Android/MXRAndroidSystem.Initialization.cs.meta
- Assets/MXR.SDK/Runtime/Android/MXRAndroidSystem.Messages.cs
- Assets/MXR.SDK/Runtime/Android/MXRAndroidSystem.Messages.cs.meta
- Assets/MXR.SDK/Runtime/Android/MXRAndroidSystem.cs
Refactored `MXRAndroidSystem` into partial classes to improve code organization and maintainability.
Split the monolithic `MXRAndroidSystem.cs` file into multiple partial class files:
- `MXRAndroidSystem.Commands.cs`: Handles command execution from the MXR Admin App
- `MXRAndroidSystem.Initialization.cs`: Manages system startup and configuration
- `MXRAndroidSystem.Messages.cs`: Processes incoming messages from the Admin App
> CU-868ex4jw0: MXRAndroidSystem Partial Classes

- Assets/MXR.SDK/Runtime/Android/MXRAndroidSystem.Messages.cs
- Assets/MXR.SDK/package.json
Fix compilation error from missing property and bump version.
> Streaming Code Json

- Assets/MXR.SDK/Runtime/Android/MXRAndroidSystem.Commands.cs
- Assets/MXR.SDK/Runtime/IMXRSystem.cs
- Assets/MXR.SDK/Runtime/Types/RuntimeTypes.cs
- Assets/MXR.SDK/Runtime/Types/StatusTypes.cs
- Assets/MXR.SDK/package.json
Also changed some code for compatibility with C# 7.3
> CU-868fevt9b: Add CustomLauncherSettings.orderedCategories
