- Assets/MXR.SDK/Plugins/Android/NativeUtils.java
- Assets/MXR.SDK/Runtime/Android/Utils/MXRAndroidUtils.Apps.cs
We sometimes need to know which version of the admin app (aka package) we are talking to. This PR adds an AndroidUtil that will retrieve this packageName (or null).
> 3y25n4z - Add Util to get the installed admin app package name

- Assets/MXR.SDK/package.json
Once merged, we'll create a new git tag for `v1.0.1` so that openupm can pick it up. PR #13 will fix an important missing readme meta file that seems to prevent Unity builds. CI currently doesn't auto bump semantic release, but that can be enabled after this so that tags will be automatically created and picked up by OpenUPM
> Bump to 1.0.1 | Merge only after PR #13 !

- Assets/MXR.SDK/Runtime/Types/RuntimeTypes.cs
isPasscodeEnabled boolean is true when passcodes have been enabled on the Device Settings tab. Can be used to show a lock button when the device can be locked.
> Added RuntimeSettingsSummary.isPasscodeEnabled

- Assets/MXR.SDK/Runtime/Types/StatusTypes.cs
This field is used to help the home screen determine which approved app was last in the foreground
> Add lastForegroundAppForShortcutMenu field to DeviceStatus

- Assets/MXR.SDK/package.json
OpenUPM release blocked as new tag was created but package.json version wasn't changed.
> Version bump to 1.0.5

- Assets/MXR.SDK/Plugins/Android/AdminAppMessengerManager.java
- Assets/MXR.SDK/Runtime/Android/MXRAndroidSystem.cs
- Assets/MXR.SDK/Runtime/Editor/MXREditorSystem.cs
- Assets/MXR.SDK/Runtime/IMXRSystem.cs
- Assets/MXR.SDK/Runtime/Types/WifiTypes.cs
Implemented Enterprise Wifi Network functionality so that the Home Screen can send payloads for the `EnterpriseWifiConnectionRequest`to the Admin app
Added `ConnectToWifiEnterpriseNetwork` interface function to `IMXRSystem`
Removed superfluous comment from `NetworkType`
Other notes, could we eventually refactor our interface functions so that each function has a prefix of `I`
> Added Enterprise Wifi Network functionality to SDK

- Assets/MXR.SDK/Samples/Scripts/ImageDownloader.cs
- Assets/MXR.SDK/Samples/Scripts/LibraryPanel.cs
- Assets/MXR.SDK/Samples/Scripts/RuntimeAppCell.cs
- Assets/MXR.SDK/Samples/Scripts/VideoCell.cs
- Assets/MXR.SDK/Samples/Scripts/WebXRAppCell.cs
`ImageDownloader` is a utility in our Samples, used for the Library sample specifically. However it's often a starting point for customer integration. 
Previously some locally stored images were not loading correctly due to not being able to "resolve host" because we used Unity's `WWW` class for them which is actually meant for web requests and is also obsolete. 
Instead we now use .NET's `WebClient` class for remote (URL) images and .NET's `File` class for local ones.
- ImageDownloader offers separate methods to load images from URL and disk, along with a general purpose Load method.
- ImageDownloader is no longer MonoBehaviour based.
- Old methods in ImageDownloader deprecated with warning but remain compatible with the new download logic.
- Files.zip updated with new icon files for …
> Correctly handle remote URL and local file locations in ImageDownloader

- Assets/MXR.SDK/Plugins/Android/AdminAppMessengerManager.java
- Assets/MXR.SDK/Plugins/Android/NativeUtils.java
- Assets/MXR.SDK/Runtime/Android/MXRAndroidSystem.cs
- Assets/MXR.SDK/Runtime/Android/Utils/MXRAndroidUtils.Apps.cs
- Assets/MXR.SDK/Runtime/Android/Utils/MXRAndroidUtils.Bluetooth.cs
- Assets/MXR.SDK/Runtime/Android/Utils/MXRAndroidUtils.cs
- Assets/MXR.SDK/Runtime/Editor/MXREditorSystem.cs
- Assets/MXR.SDK/Runtime/IMXRSystem.cs
- Assets/MXR.SDK/Runtime/MXRManager.cs
- Implemented IsAdminAppInstalled by using getInstalledAdminAdminServiceComponent on Android
- On Editor it's implemented by checking if Files/MightyImmersion folder exists
- Also deprecated (but not removed) IMXRSystem.IsAvailable and introduced IsConnectedToAdminApp that serves the same purpose for more clarity
> Added IsAdminAppInstalled to IMXRSystem

- Assets/MXR.SDK/Runtime/Android/MXRAndroidSystem.cs
- Assets/MXR.SDK/Runtime/Android/Utils/MXRAndroidUtils.Apps.cs
- Assets/MXR.SDK/Runtime/Android/Utils/MXRAndroidUtils.Device.cs
- Assets/MXR.SDK/Runtime/Android/Utils/MXRAndroidUtils.cs
- README.md
- On Android 30 and above, we check for Manage All Files permission before trying to read external json files. If permissions aren't available, we try cached/internal json files. If they don't exist, we skip json based init and wait for the messenger to receive the runtime settings summary and device status.
> Fallback on messenger to init if no storage permissions found

- Assets/MXR.SDK/Plugins/Android/AdminAppMessengerManager.java
- Assets/MXR.SDK/Runtime/MXRManager.cs
Fixed issue where the SDK AdminAppMessengerManager would fail to bind the Admin App and Home screen, due to a rare case in which the package name "com.mightyimmersion.mightyplatform.adminapp.test" was being returned from a search prior to "com.mightyimmersion.mightyplatform.adminapp"
Added logging for the following cases
- While waiting to connect to Admin App
- While waiting for  DeviceStatus and RuntimeSettingsSummary"
> Fix issue where SDK hangs during service binding with the Home Screen

- Assets/MXR.SDK/Runtime/Types/RuntimeTypes.cs
We no longer use featureFlags, this is being made into an SDK level feature.
> Added disableGazeInput in RuntimeSettingsSummary

- Assets/MXR.SDK/Runtime/Android/AdminAppMessengerManager.cs
- Assets/MXR.SDK/Runtime/Android/MXRAndroidSystem.cs
- Assets/MXR.SDK/Runtime/Android/Utils/MXRAndroidUtils.Apps.cs
- Assets/MXR.SDK/Runtime/Android/Utils/MXRAndroidUtils.Bluetooth.cs
- Assets/MXR.SDK/Runtime/Android/Utils/MXRAndroidUtils.Device.cs
- Assets/MXR.SDK/Runtime/Android/Utils/MXRAndroidUtils.cs
- Assets/MXR.SDK/Runtime/Android/Utils/SafeJNI.cs
- Assets/MXR.SDK/Runtime/Android/Utils/SafeJNI.cs.meta
- Assets/MXR.SDK/Runtime/Utils/MXRStorage.cs
- Assets/MXR.SDK/package.json
- ProjectSettings/ProjectVersion.txt
* SafeJNI class introduced to offer try/catch wrapped JNI calls
This allows us to log JNI exceptions without stopping executing for code. Example:
```
void GetSomething(AndroidJavaObject obj){
var flag = obj.SafeGet<AndroidJavaObject>("getInternalObject"); // Prints exception if error occurs
Debug.Log("Success " + flag != default); // Works even if the above call fails
}
```
The general idea is that in JNI we don't really care about exceptions, the errors just get logged and we only check if the call was successful. But if it isn't, code execution stops.
Future improvements such as specifying default value on failure can be added if we need them.
* Caching of JNI values where they don't change:
- AndroidSDKAsInt
- TargetSDKLevelAsInt
- DeviceManufacturer
- DeviceModel
- DeviceProduct
* …
> JNI improvements

- Assets/MXR.SDK/Runtime/Android/Utils/MXRAndroidUtils.Apps.cs
During the update to `SafeJNI` class, we stopped returning the value from this method properly
> Fix MXRAndroidUtils.GetInstalledPackageVersionName

- Assets/MXR.SDK/Runtime/Editor/MXREditorSystem.cs
The Disable Wifi action was previous logging as 'Disabled Kiosk Mode', so this has been corrected.
> chore[logs]: Editor System fixing disable wifi log

- Assets/MXR.SDK/Runtime/Types/RuntimeTypes.cs
New types introduced for library card customization:
* `public class CardSettings`
- `public bool showTitle`
- `public bool showContentType`
* `public class LibrarySettings`
- `public CardSettings cardSettings`
Object `public LibrarySettings librarySettings` added to `CustomLauncherSettings` class
Access via:
* `RuntimeSettingsSummary.customLauncher.librarySettings.cardSettings.showTitle`
* `RuntimeSettingsSummary.customLauncher.librarySettings.cardSettings.showContentType`
> Added types for card customization

- Assets/MXR.SDK/Runtime/Types/RuntimeTypes.cs
- Also default showTitle and showContentType in CardSettings to true
- Updated some comments to be more descriptive as the hierarchy evolves
> Library panel categories customization

- Assets/MXR.SDK/Runtime/Types/RuntimeTypes.cs
* `alignment` field was previously used for horizontal alignment. It has been renamed to `horizontalAlignment` and `verticalAlignment` has been added
> Added GridSettings.verticalAlignment and horizontalAlignment

- Assets/MXR.SDK/Runtime/Types/RuntimeTypes.cs
Rotation and packing fields were previously inside CustomLauncherSettings at the root level. They've been moved to BackgroundSettings class
> CU-868a54vcu: Moved skybox related settings to backgroundSettings object

- Assets/MXR.SDK/Runtime/Android/Utils/MXRAndroidUtils.Apps.cs
- Assets/MXR.SDK/Runtime/Android/Utils/MXRAndroidUtils.Device.cs
- Assets/MXR.SDK/Runtime/Android/Utils/MXRPicoUtils.cs
- Assets/MXR.SDK/Runtime/Android/Utils/MXRPicoUtils.cs.meta
* `MXRPicoUtils.LaunchIntentAction` allows launching an intent with an action string
* `OpenSystemUpdateUI` uses it with the OPEN_SYSTEM_UPDATE action
Deprecated with no breaking changes:
___MXRAndroidUtils.Device.cs___
* `PicoUIVersion` in favor of `MXRPicoUtils.PUIVersion`
* `IsPicoUI4` in favor of `MXRPicoUtils.IsPUI4`
___MXRAndroidUtils.Apps.cs___
* `LaunchAppWithIntentAction` in favor of `LaunchIntentAction` to match the native method name
* `GetSystemProperty` introduced. `GetProductName` is now deprecated and forwards the call to it with `"ro.product.name"` as the parameter
Fixed some incorrect code doc comments in MXRAndroidUtils.Device.cs
> Introduced MXRPicoUtils for Pico specific utilities

- Assets/MXR.SDK/Plugins/Android/NativeUtils.java
- Assets/MXR.SDK/Runtime/Android/MXRAndroidSystem.cs
- Assets/MXR.SDK/Runtime/Android/Utils/MXRAndroidUtils.Apps.cs
- Assets/MXR.SDK/Runtime/MXRManager.cs
NativeUtils.java now has a getInstalledAdminAppVersionName() method to retrieve the version name of the admin app
MXRAndroidUtils changes:
* MinAdminAppVersionSupportingDeviceData defines 1.7.74 as the minimum admin app version supporting DeviceData
* IsDeviceDataSupported returns if the admin app supports DeviceData features.
* GetAdminAppVersionName() that returns the version name as a string
* GetAdminAppVersion() that returns the version as a Version object
MXRManager now waits for DeviceData for its initialization only if the installed admin app supports DeviceData features.
MXRAndroidSystem initializes DeviceData (including initializing from the last cached json) only if admin app supports DeviceData.
Note: There's no version check on MXRAndroidSystem.cs#187. This allows DeviceData …
> CU-868brkjk3: Gate DeviceData code based on admin app version

- Assets/MXR.SDK/Runtime/Android/Utils/MXRAndroidUtils.Apps.cs
When running in the Unity Editor, we always support DeviceData because the sample deviceData.json is used by MXREditorSystem for simulating DeviceData.
A similar editor check has been added to GetAdminAppVersion() which returns null when running in the editor.
Not having these checks would cause the code to execute JNI calls when in the editor which fails.
> Added editor checks to GetAdminAppVersion() and IsDeviceDataSupported

- Assets/MXR.SDK/Runtime/Android/Utils/MXRPicoUtils.cs
Added new Pico utility methods to check PUI version 5 and open general settings
- Added `OpenSettingsUI()` method to launch Pico's general settings UI
- Added `IsPUI5` property to check if device is running PUI version 5.x.x
- Both new additions include safety checks for non-Pico devices
> CU-868b8nkvj: Extend Pico Utils with OpenSettingsUI and IsPUI5

- Assets/MXR.SDK/Runtime/Types/RuntimeTypes.cs
Currently EnvironmentType enum only has MXRUS. Other formats to be introduced when their capability is added to the official MXR home screen
> CU-868b6vg7q: 3D environment RuntimeSettingsSummary types

- Assets/MXR.SDK/Runtime/Types/DeviceTypes.cs
Added controller data field to DeviceData class.
Added a new `controllerData` field of type `ControllerData` to the `DeviceData` class in the DeviceTypes.cs file. 
This change allows us to utilize and consume the new Controller Battery API changes that were made on the Admin App side.
> CU-868d5ju8b: Consume New Controller Api

- Assets/MXR.SDK/Runtime/Types/RuntimeTypes.cs
Added a new `autoCenterLibraryPanel` boolean property to the `CustomLauncherSettings` class.
Added a new boolean property `autoCenterLibraryPanel` to the `CustomLauncherSettings` class in `RuntimeTypes.cs`. This property includes XML documentation explaining that when enabled, the Library Panel will follow the user's head to stay in their field of view, and when disabled, the panel will remain in a fixed location requiring manual recentering.
> CU-868efuftr: Add Auto Center To Runtime Settings

- Assets/MXR.SDK/Plugins/Android/AdminAppMessageTypes.java
- Assets/MXR.SDK/Plugins/Android/AdminAppMessengerManager.java
- Assets/MXR.SDK/Runtime/Android/MXRAndroidSystem.Messages.cs
- Assets/MXR.SDK/Runtime/Android/MXRAndroidSystem.cs
- Assets/MXR.SDK/Runtime/Editor/MXREditorSystem.cs
- Assets/MXR.SDK/Runtime/IMXRSystem.cs
- Assets/MXR.SDK/Runtime/Types/StatusTypes.cs
Renamed all "streaming" terminology to "casting" throughout the SDK to better reflect the functionality.
- Renamed message types `GET_STREAMING_CODE` to `GET_CASTING_CODE` and `STOP_STREAMING` to `STOP_CASTING`
- Renamed constant `STREAMING_CODE` to `CASTING_CODE`
- Updated method names in `AdminAppMessengerManager.java`:
- `requestStreamingCodeAsync()` → `requestCastingCodeAsync()`
- `stopStreamingAsync()` → `stopCastingAsync()`
- Updated handler methods in `MXRAndroidSystem.Messages.cs`:
- `HandleStreamingCode()` → `HandleCastingCode()`
- Renamed class `StreamingCodeStatus` to `CastingCodeStatus`
- Updated all related properties, methods, and event handlers in `MXRAndroidSystem.cs`, `MXREditorSystem.cs`, and `IMXRSystem.cs`
> CU-868evjr20: Screen Casting Rename

- Assets/MXR.SDK/Runtime/Android/AdminAppMessengerManager.cs
- Assets/MXR.SDK/Runtime/Android/MXRAndroidSystem.Messages.cs
- Assets/MXR.SDK/Runtime/Android/MXRAndroidSystem.cs
Improved error handling and logging in the MXR SDK Android communication layer.
- Added robust exception handling around message processing in `AdminAppMessengerManager` and `MXRAndroidSystem.Messages`
- Added detailed error logging for JSON deserialization failures and other exceptions
- Added null/empty checks for JSON data before processing
- Added handling for unknown message types
- Fixed a bug in `HandleWifiNetworks` where the wrong variable was being updated
- Added a constant TAG for consistent logging in `AdminAppMessengerManager`
- Improved the `UnescapeJsonIfNeeded` method with better error handling and null checks
> Add Try-Catch Safety

- Assets/MXR.SDK/package.json
Bumped the ManageXR Unity SDK version from 1.0.38 to 1.0.39.
Updated the package version in `Assets/MXR.SDK/package.json` from 1.0.38 to 1.0.39.
> Version bump to 1.0.39

- Assets/MXR.SDK/Plugins/Android/AdminAppMessageTypes.java
- Assets/MXR.SDK/Plugins/Android/AdminAppMessengerManager.java
- Assets/MXR.SDK/Runtime/Android/MXRAndroidSystem.cs
- Assets/MXR.SDK/Runtime/Editor/MXREditorSystem.cs
- Assets/MXR.SDK/Runtime/IMXRSystem.cs
- Assets/MXR.SDK/package.json
Added device log upload functionality to the Android admin app messenger system.
- Added a new message type `UPLOAD_DEVICE_LOGS` (value 23) in `AdminAppMessageTypes.java`
- Implemented a new method `uploadDeviceLogsAsync()` in `AdminAppMessengerManager.java` that sends the new message type
- Added a corresponding `UploadDeviceLogs()` method in `MXRAndroidSystem.cs` that calls the Java implementation through JNI
This change enables remote collection of device logs through the admin app, which will help with debugging and troubleshooting issues on deployed devices without requiring physical access to the hardware.
> CU-868fmnk6b upload device logs bridge
